// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Calculator

#ifndef _CALCULATOR_UI_H
#define _CALCULATOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_img_bg;
extern lv_obj_t *ui_lbl_title;
extern lv_obj_t *ui_pnl_close;
extern lv_obj_t *ui_png_answer;
extern lv_obj_t *ui_lbl_answer;
extern lv_obj_t *ui_img_pad_bg;
extern lv_obj_t *ui_pad_c;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_pad_eql_s;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_pad_dev;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_pad_multy;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_pad_minus;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_pad_9;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_pad_8;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_pad_7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_pad_4;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_pad_5;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_pad_6;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_pad_plus;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_pad_1;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_pad_2;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_pad_3;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_pad_eql_b;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_pad_0_b;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_pad_dot;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_pnl_selected;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1548360417);   // assets/calculator-1.png
LV_IMG_DECLARE( ui_img_pad_bg_png);   // assets/pad bg.png
LV_IMG_DECLARE( ui_img_pad_single_png);   // assets/pad single.png
LV_IMG_DECLARE( ui_img_pad_single_v_png);   // assets/pad single v.png
LV_IMG_DECLARE( ui_img_pad_singl_h_png);   // assets/pad singl h.png
LV_IMG_DECLARE( ui_img_selected_png);   // assets/selected.png

LV_FONT_DECLARE( ui_font_Pix12);
LV_FONT_DECLARE( ui_font_Pix16);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
