// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: clock

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Imagebg;
lv_obj_t *ui_Imageberry;
lv_obj_t *ui_Labeldate;
lv_obj_t *ui_Labelhour;
lv_obj_t *ui_Labelabbr;
lv_obj_t *ui_Labelday;
lv_obj_t *ui_Labeltt;
lv_obj_t *ui_Labelht;
lv_obj_t *ui_Labeltemp;
lv_obj_t *ui_Labelhum;
lv_obj_t *ui_Imagewifi;
lv_obj_t *ui_Labelssid;
lv_obj_t *ui_Labelrssi;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Labelfeelslike;
lv_obj_t *ui_Labelc;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Labelcolon;
lv_obj_t *ui_Labelmin;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_feelslike[1] = {&ui_img_feelslike2_png};
const lv_img_dsc_t *ui_imgset_temp[1] = {&ui_img_temp01_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
