// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: clock

#ifndef _CLOCK_UI_H
#define _CLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Imagebg;
extern lv_obj_t *ui_Imageberry;
extern lv_obj_t *ui_Labeldate;
extern lv_obj_t *ui_Labelhour;
extern lv_obj_t *ui_Labelabbr;
extern lv_obj_t *ui_Labelday;
extern lv_obj_t *ui_Labeltt;
extern lv_obj_t *ui_Labelht;
extern lv_obj_t *ui_Labeltemp;
extern lv_obj_t *ui_Labelhum;
extern lv_obj_t *ui_Imagewifi;
extern lv_obj_t *ui_Labelssid;
extern lv_obj_t *ui_Labelrssi;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Labelfeelslike;
extern lv_obj_t *ui_Labelc;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Labelcolon;
extern lv_obj_t *ui_Labelmin;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_bg_png);   // assets/bg.png
LV_IMG_DECLARE( ui_img_strawberry_png);   // assets/Strawberry.png
LV_IMG_DECLARE( ui_img_wifi_png);   // assets/wifi.png
LV_IMG_DECLARE( ui_img_temp01_png);   // assets/temp01.png
LV_IMG_DECLARE( ui_img_feelslike2_png);   // assets/feelslike2.png
LV_IMG_DECLARE( ui_img_range_png);   // assets/range.png

LV_FONT_DECLARE( ui_font_vag18);
LV_FONT_DECLARE( ui_font_vag20);
LV_FONT_DECLARE( ui_font_vag45);
LV_FONT_DECLARE( ui_font_vag50);
LV_FONT_DECLARE( ui_font_vag70);
LV_FONT_DECLARE( ui_font_vag80);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
