// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: clock

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Imagebg = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Imagebg, &ui_img_bg_png);
lv_obj_set_width( ui_Imagebg, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_Imagebg, LV_SIZE_CONTENT);   /// 170
lv_obj_set_align( ui_Imagebg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Imagebg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Imagebg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Imageberry = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Imageberry, &ui_img_strawberry_png);
lv_obj_set_width( ui_Imageberry, LV_SIZE_CONTENT);  /// 88
lv_obj_set_height( ui_Imageberry, LV_SIZE_CONTENT);   /// 130
lv_obj_set_x( ui_Imageberry, 111 );
lv_obj_set_y( ui_Imageberry, 6 );
lv_obj_set_align( ui_Imageberry, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Imageberry, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Imageberry, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Labeldate = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labeldate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labeldate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labeldate, 111 );
lv_obj_set_y( ui_Labeldate, 8 );
lv_obj_set_align( ui_Labeldate, LV_ALIGN_CENTER );
lv_label_set_text(ui_Labeldate,"--");
lv_obj_set_style_text_font(ui_Labeldate, &ui_font_vag50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labelhour = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labelhour, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelhour, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelhour, -226 );
lv_obj_set_y( ui_Labelhour, -15 );
lv_obj_set_align( ui_Labelhour, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Labelhour,"--");
lv_obj_set_style_text_color(ui_Labelhour, lv_color_hex(0x91142F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelhour, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelhour, &ui_font_vag80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labelabbr = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labelabbr, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelabbr, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelabbr, 208 );
lv_obj_set_y( ui_Labelabbr, -36 );
lv_obj_set_align( ui_Labelabbr, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Labelabbr,"__");
lv_obj_set_style_text_color(ui_Labelabbr, lv_color_hex(0x91142F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelabbr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelabbr, &ui_font_vag20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labelday = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labelday, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelday, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelday, 114 );
lv_obj_set_y( ui_Labelday, 39 );
lv_obj_set_align( ui_Labelday, LV_ALIGN_CENTER );
lv_label_set_text(ui_Labelday,"--");
lv_obj_set_style_text_font(ui_Labelday, &ui_font_vag20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labeltt = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labeltt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labeltt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labeltt, -102 );
lv_obj_set_y( ui_Labeltt, 37 );
lv_obj_set_align( ui_Labeltt, LV_ALIGN_CENTER );
lv_label_set_text(ui_Labeltt,"T :");
lv_obj_set_style_text_color(ui_Labeltt, lv_color_hex(0x91142F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labeltt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labeltt, &ui_font_vag18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labelht = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labelht, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelht, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelht, -104 );
lv_obj_set_y( ui_Labelht, 57 );
lv_obj_set_align( ui_Labelht, LV_ALIGN_CENTER );
lv_label_set_text(ui_Labelht,"H :");
lv_obj_set_style_text_color(ui_Labelht, lv_color_hex(0x91142F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelht, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelht, &ui_font_vag18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labeltemp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labeltemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labeltemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labeltemp, 72 );
lv_obj_set_y( ui_Labeltemp, 37 );
lv_obj_set_align( ui_Labeltemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Labeltemp,"__");
lv_obj_set_style_text_color(ui_Labeltemp, lv_color_hex(0x91142F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labeltemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labeltemp, &ui_font_vag20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labelhum = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labelhum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelhum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelhum, 73 );
lv_obj_set_y( ui_Labelhum, 57 );
lv_obj_set_align( ui_Labelhum, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Labelhum,"__");
lv_obj_set_style_text_color(ui_Labelhum, lv_color_hex(0x91142F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelhum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelhum, &ui_font_vag20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Imagewifi = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Imagewifi, &ui_img_wifi_png);
lv_obj_set_width( ui_Imagewifi, LV_SIZE_CONTENT);  /// 12
lv_obj_set_height( ui_Imagewifi, LV_SIZE_CONTENT);   /// 12
lv_obj_set_x( ui_Imagewifi, -148 );
lv_obj_set_y( ui_Imagewifi, -73 );
lv_obj_set_align( ui_Imagewifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Imagewifi, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Imagewifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Labelssid = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labelssid, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelssid, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelssid, 23 );
lv_obj_set_y( ui_Labelssid, -74 );
lv_obj_set_align( ui_Labelssid, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Labelssid,"...");
lv_obj_set_style_text_color(ui_Labelssid, lv_color_hex(0x0E0E0E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelssid, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelssid, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labelrssi = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labelrssi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelrssi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelrssi, 294 );
lv_obj_set_y( ui_Labelrssi, -74 );
lv_obj_set_align( ui_Labelrssi, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Labelrssi,"..");
lv_label_set_recolor(ui_Labelrssi,"true");
lv_obj_set_style_text_color(ui_Labelrssi, lv_color_hex(0x0E0E0E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelrssi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelrssi, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_temp01_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Image1, -136 );
lv_obj_set_y( ui_Image1, 46 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Labelfeelslike = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labelfeelslike, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelfeelslike, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelfeelslike, 157 );
lv_obj_set_y( ui_Labelfeelslike, 49 );
lv_obj_set_align( ui_Labelfeelslike, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Labelfeelslike,"__");
lv_obj_set_style_text_color(ui_Labelfeelslike, lv_color_hex(0x91142F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelfeelslike, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelfeelslike, &ui_font_vag50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labelc = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labelc, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelc, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelc, 219 );
lv_obj_set_y( ui_Labelc, 55 );
lv_obj_set_align( ui_Labelc, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Labelc,"_");
lv_obj_set_style_text_color(ui_Labelc, lv_color_hex(0x91142F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelc, &ui_font_vag20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image3, &ui_img_feelslike2_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 28
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 41
lv_obj_set_x( ui_Image3, -22 );
lv_obj_set_y( ui_Image3, 44 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image2, &ui_img_range_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 10
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 10
lv_obj_set_x( ui_Image2, 125 );
lv_obj_set_y( ui_Image2, -74 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Labelcolon = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labelcolon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelcolon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelcolon, -55 );
lv_obj_set_y( ui_Labelcolon, -18 );
lv_obj_set_align( ui_Labelcolon, LV_ALIGN_CENTER );
lv_label_set_text(ui_Labelcolon,":");
lv_obj_set_style_text_color(ui_Labelcolon, lv_color_hex(0x91142F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelcolon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelcolon, &ui_font_vag80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labelmin = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Labelmin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelmin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelmin, 117 );
lv_obj_set_y( ui_Labelmin, -15 );
lv_obj_set_align( ui_Labelmin, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Labelmin,"--");
lv_obj_set_style_text_color(ui_Labelmin, lv_color_hex(0x91142F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelmin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelmin, &ui_font_vag80, LV_PART_MAIN| LV_STATE_DEFAULT);

}
