// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Calculator

#include "../ui.h"


// COMPONENT btn bg

lv_obj_t *ui_btn_bg_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_btn_bg;
cui_btn_bg = lv_obj_create(comp_parent);
lv_obj_set_width( cui_btn_bg, 25);
lv_obj_set_height( cui_btn_bg, 25);
lv_obj_set_x( cui_btn_bg, -45 );
lv_obj_set_y( cui_btn_bg, -93 );
lv_obj_clear_flag( cui_btn_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_btn_bg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_btn_bg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_btn_bg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_btn_bg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_btn_bg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BTN_BG_NUM);
children[UI_COMP_BTN_BG_BTN_BG] = cui_btn_bg;
lv_obj_add_event_cb(cui_btn_bg, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_btn_bg, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_btn_bg_create_hook(cui_btn_bg);
return cui_btn_bg; 
}

