// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Bike_dashboard

#ifndef _BIKE_DASHBOARD_UI_H
#define _BIKE_DASHBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void compass1_Animation( lv_obj_t *TargetObject, int delay);
void compass2_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_img_guage_bg;
extern lv_obj_t *ui_compass;
extern lv_obj_t *ui_compass_overlay;
extern lv_obj_t *ui_img_devider;
extern lv_obj_t *ui_cont_speed_num;
extern lv_obj_t *ui_speed_num;
extern lv_obj_t *ui_speed_num1;
extern lv_obj_t *ui_speed_num2;
extern lv_obj_t *ui_speed_num3;
extern lv_obj_t *ui_speed_num4;
extern lv_obj_t *ui_speed_num5;
extern lv_obj_t *ui_speed_num6;
extern lv_obj_t *ui_speed_num7;
extern lv_obj_t *ui_speed_num8;
extern lv_obj_t *ui_speed_num9;
extern lv_obj_t *ui_speed_num10;
void ui_event_slider_speed( lv_event_t * e);
extern lv_obj_t *ui_slider_speed;
extern lv_obj_t *ui_lbl_speed;
extern lv_obj_t *ui_lbl_speed1;
extern lv_obj_t *ui_lbl_trip_value;
extern lv_obj_t *ui_lbl_trip;
extern lv_obj_t *ui_lbl_battery_value;
extern lv_obj_t *ui_roller_mode;
extern lv_obj_t *ui_slider_range;
extern lv_obj_t *ui_bar_battery;
extern lv_obj_t *ui_img_battery;
extern lv_obj_t *ui_lbl_range1;
extern lv_obj_t *ui_lbl_range;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_images_bg_png);   // assets/images/bg.png
LV_IMG_DECLARE( ui_img_images_guage_bg_png);   // assets/images/guage bg.png
LV_IMG_DECLARE( ui_img_images_compas_png);   // assets/images/compas.png
LV_IMG_DECLARE( ui_img_images_compass_overlay_png);   // assets/images/compass overlay.png
LV_IMG_DECLARE( ui_img_images_devider_png);   // assets/images/devider.png
LV_IMG_DECLARE( ui_img_images_guage_indicator_png);   // assets/images/guage indicator.png
LV_IMG_DECLARE( ui_img_images_range_bg_png);   // assets/images/range bg.png
LV_IMG_DECLARE( ui_img_images_range_knob_png);   // assets/images/range knob.png
LV_IMG_DECLARE( ui_img_images_battery_indicator_png);   // assets/images/battery indicator.png
LV_IMG_DECLARE( ui_img_images_battery_bg_png);   // assets/images/battery bg.png
LV_IMG_DECLARE( ui_img_images_guage_bg_1_png);   // assets/images/guage bg_1.png

LV_FONT_DECLARE( ui_font_Hollow18);
LV_FONT_DECLARE( ui_font_Hollow22);
LV_FONT_DECLARE( ui_font_Hollow38);
LV_FONT_DECLARE( ui_font_Hollow85);
LV_FONT_DECLARE( ui_font_Inter12);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
