// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: T-Display

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x457A9C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar_Battery = lv_bar_create(ui_Screen1);
lv_obj_set_width( ui_Bar_Battery, 42);
lv_obj_set_height( ui_Bar_Battery, 112);
lv_obj_set_x( ui_Bar_Battery, 108 );
lv_obj_set_y( ui_Bar_Battery, -3 );
lv_obj_set_align( ui_Bar_Battery, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar_Battery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar_Battery, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_Battery, lv_color_hex(0x19E500), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_Battery, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Image_Car = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_Car, &ui_img__car_png);
lv_obj_set_width( ui_Image_Car, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_Image_Car, LV_SIZE_CONTENT);   /// 170
lv_obj_set_align( ui_Image_Car, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_Car, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_Car, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


}
