// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: PV Dashboard

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cont_guage_home = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Cont_guage_home);
lv_obj_set_width( ui_Cont_guage_home, 108);
lv_obj_set_height( ui_Cont_guage_home, 108);
lv_obj_set_x( ui_Cont_guage_home, -14 );
lv_obj_set_y( ui_Cont_guage_home, 11 );
lv_obj_set_align( ui_Cont_guage_home, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Cont_guage_home, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_guage_home = lv_img_create(ui_Cont_guage_home);
lv_img_set_src(ui_img_guage_home, &ui_img_images_home_guage_png);
lv_obj_set_width( ui_img_guage_home, LV_SIZE_CONTENT);  /// 108
lv_obj_set_height( ui_img_guage_home, LV_SIZE_CONTENT);   /// 108
lv_obj_set_align( ui_img_guage_home, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_guage_home, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_guage_home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_needle_home = lv_img_create(ui_Cont_guage_home);
lv_img_set_src(ui_img_needle_home, &ui_img_images_home_needle_png);
lv_obj_set_width( ui_img_needle_home, LV_SIZE_CONTENT);  /// 108
lv_obj_set_height( ui_img_needle_home, LV_SIZE_CONTENT);   /// 108
lv_obj_set_align( ui_img_needle_home, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_needle_home, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_needle_home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_home_kV = lv_label_create(ui_Cont_guage_home);
lv_obj_set_width( ui_Label_home_kV, 60);
lv_obj_set_height( ui_Label_home_kV, 31);
lv_obj_set_align( ui_Label_home_kV, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_home_kV,"0");
lv_obj_set_style_text_color(ui_Label_home_kV, lv_color_hex(0x1EAEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_home_kV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_home_kV, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_home_kV, &ui_font_Be30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cont_guage_pv = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Cont_guage_pv);
lv_obj_set_width( ui_Cont_guage_pv, 108);
lv_obj_set_height( ui_Cont_guage_pv, 108);
lv_obj_set_x( ui_Cont_guage_pv, -134 );
lv_obj_set_y( ui_Cont_guage_pv, 11 );
lv_obj_set_align( ui_Cont_guage_pv, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Cont_guage_pv, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_guage_pv = lv_img_create(ui_Cont_guage_pv);
lv_img_set_src(ui_img_guage_pv, &ui_img_images_pv_guage_png);
lv_obj_set_width( ui_img_guage_pv, LV_SIZE_CONTENT);  /// 108
lv_obj_set_height( ui_img_guage_pv, LV_SIZE_CONTENT);   /// 108
lv_obj_set_align( ui_img_guage_pv, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_guage_pv, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_guage_pv, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_needle_pv = lv_img_create(ui_Cont_guage_pv);
lv_img_set_src(ui_img_needle_pv, &ui_img_images_pv_needle_png);
lv_obj_set_width( ui_img_needle_pv, LV_SIZE_CONTENT);  /// 108
lv_obj_set_height( ui_img_needle_pv, LV_SIZE_CONTENT);   /// 108
lv_obj_set_align( ui_img_needle_pv, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_needle_pv, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_needle_pv, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_img_needle_pv,1800);

ui_Label_pv_kV = lv_label_create(ui_Cont_guage_pv);
lv_obj_set_width( ui_Label_pv_kV, 60);
lv_obj_set_height( ui_Label_pv_kV, 31);
lv_obj_set_align( ui_Label_pv_kV, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_pv_kV,"0");
lv_obj_set_style_text_color(ui_Label_pv_kV, lv_color_hex(0xFF9C56), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_pv_kV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_pv_kV, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_pv_kV, &ui_font_Be30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cont_power = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Cont_power);
lv_obj_set_width( ui_Cont_power, 254);
lv_obj_set_height( ui_Cont_power, 92);
lv_obj_set_align( ui_Cont_power, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Cont_power, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_outline_power = lv_img_create(ui_Cont_power);
lv_img_set_src(ui_img_outline_power, &ui_img_images_outline_power_png);
lv_obj_set_width( ui_img_outline_power, LV_SIZE_CONTENT);  /// 248
lv_obj_set_height( ui_img_outline_power, LV_SIZE_CONTENT);   /// 89
lv_obj_set_align( ui_img_outline_power, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_outline_power, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_outline_power, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_img_outline_power, lv_color_hex(0x989898), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_img_outline_power, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Cont_power);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -60 );
lv_obj_set_y( ui_Label4, -1 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"kW");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &ui_font_Be15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Cont_power);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 61 );
lv_obj_set_y( ui_Label1, -1 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"kW");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_Be15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Cont_power);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 1 );
lv_obj_set_y( ui_Label2, 27 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"POWER");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &ui_font_Be15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Cont_power);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -109 );
lv_obj_set_y( ui_Label3, 27 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"PV");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &ui_font_Be15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Cont_power);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 100 );
lv_obj_set_y( ui_Label5, 27 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"HOME");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &ui_font_Be15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cont_kWh = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Cont_kWh);
lv_obj_set_width( ui_Cont_kWh, 254);
lv_obj_set_height( ui_Cont_kWh, 88);
lv_obj_set_x( ui_Cont_kWh, 0 );
lv_obj_set_y( ui_Cont_kWh, 81 );
lv_obj_set_align( ui_Cont_kWh, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Cont_kWh, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_outline_kWh = lv_img_create(ui_Cont_kWh);
lv_img_set_src(ui_img_outline_kWh, &ui_img_images_outline_kwh_png);
lv_obj_set_width( ui_img_outline_kWh, LV_SIZE_CONTENT);  /// 248
lv_obj_set_height( ui_img_outline_kWh, LV_SIZE_CONTENT);   /// 89
lv_obj_set_x( ui_img_outline_kWh, 0 );
lv_obj_set_y( ui_img_outline_kWh, -1 );
lv_obj_set_align( ui_img_outline_kWh, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_outline_kWh, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_outline_kWh, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_img_outline_kWh, lv_color_hex(0x989898), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_img_outline_kWh, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Cont_kWh);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 1 );
lv_obj_set_y( ui_Label6, -33 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"kWh");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &ui_font_Be15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Chart_TP = lv_chart_create(ui_Cont_kWh);
lv_obj_set_width( ui_Chart_TP, 83);
lv_obj_set_height( ui_Chart_TP, 21);
lv_obj_set_x( ui_Chart_TP, -51 );
lv_obj_set_y( ui_Chart_TP, 15 );
lv_obj_set_align( ui_Chart_TP, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart_TP, LV_CHART_TYPE_BAR);
lv_chart_set_point_count( ui_Chart_TP, 60);
lv_chart_set_range( ui_Chart_TP, LV_CHART_AXIS_PRIMARY_Y, 0, 20);
lv_chart_set_div_line_count( ui_Chart_TP, 5, 12);
lv_chart_set_axis_tick( ui_Chart_TP, LV_CHART_AXIS_PRIMARY_X, 0, 0, 10, 10, false, 12);
lv_chart_set_axis_tick( ui_Chart_TP, LV_CHART_AXIS_PRIMARY_Y, 2, 5, 2, 1, false, 10);
lv_chart_set_axis_tick( ui_Chart_TP, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
lv_chart_series_t* ui_Chart_TP_series_1 = lv_chart_add_series(ui_Chart_TP, lv_color_hex(0x9CF486), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart_TP_series_1_array[] = { 0,10,20,5,0 };
lv_chart_set_ext_y_array(ui_Chart_TP, ui_Chart_TP_series_1, ui_Chart_TP_series_1_array);
lv_obj_set_style_radius(ui_Chart_TP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Chart_TP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Chart_TP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Chart_TP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Chart_TP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_color(ui_Chart_TP, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_Chart_TP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_width(ui_Chart_TP, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Chart_TP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Chart_TP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Chart_TP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Chart_TP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_line_width(ui_Chart_TP, 2, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Chart_TP, 0, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Chart_TP, 0, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Chart_TP, 0, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Chart_TP, 0, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_set_style_outline_color(ui_Chart_TP, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Chart_TP, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Chart_TP, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Chart_TP, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Chart_TP, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Chart_TP, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Chart_TP, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Chart_TP, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_size(ui_Chart_TP, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_line_color(ui_Chart_TP, lv_color_hex(0x4040FF), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_Chart_TP, 0, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_line_width(ui_Chart_TP, 2, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Chart_TP, &ui_font_Be13, LV_PART_TICKS| LV_STATE_DEFAULT);

ui_Cont_battery = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Cont_battery);
lv_obj_set_width( ui_Cont_battery, 63);
lv_obj_set_height( ui_Cont_battery, 91);
lv_obj_set_x( ui_Cont_battery, 3 );
lv_obj_set_y( ui_Cont_battery, 0 );
lv_obj_clear_flag( ui_Cont_battery, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_battery_fill = lv_img_create(ui_Cont_battery);
lv_img_set_src(ui_img_battery_fill, &ui_img_images_battery_png);
lv_obj_set_width( ui_img_battery_fill, LV_SIZE_CONTENT);  /// 36
lv_obj_set_height( ui_img_battery_fill, LV_SIZE_CONTENT);   /// 71
lv_obj_set_x( ui_img_battery_fill, 0 );
lv_obj_set_y( ui_img_battery_fill, 1 );
lv_obj_set_align( ui_img_battery_fill, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_battery_fill, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_battery_fill, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_img_battery_fill, lv_color_hex(0xFF0000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_img_battery_fill, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_battery_knob = lv_img_create(ui_Cont_battery);
lv_img_set_src(ui_img_battery_knob, &ui_img_images_battery_knob_png);
lv_obj_set_width( ui_img_battery_knob, LV_SIZE_CONTENT);  /// 36
lv_obj_set_height( ui_img_battery_knob, LV_SIZE_CONTENT);   /// 68
lv_obj_set_align( ui_img_battery_knob, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_battery_knob, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_battery_knob, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_img_battery_knob, lv_color_hex(0xFF0000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_img_battery_knob, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_battery_icon = lv_img_create(ui_Cont_battery);
lv_img_set_src(ui_img_battery_icon, &ui_img_images_battery_icon_png);
lv_obj_set_width( ui_img_battery_icon, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_img_battery_icon, LV_SIZE_CONTENT);   /// 86
lv_obj_set_align( ui_img_battery_icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_battery_icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_battery_icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_img_battery_icon, lv_color_hex(0xF1F1F1), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_img_battery_icon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cont_mV_bar = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Cont_mV_bar);
lv_obj_set_width( ui_Cont_mV_bar, 180);
lv_obj_set_height( ui_Cont_mV_bar, 11);
lv_obj_set_align( ui_Cont_mV_bar, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_Cont_mV_bar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_mv_bar = lv_img_create(ui_Cont_mV_bar);
lv_img_set_src(ui_img_mv_bar, &ui_img_images_mv_bar_png);
lv_obj_set_width( ui_img_mv_bar, LV_SIZE_CONTENT);  /// 173
lv_obj_set_height( ui_img_mv_bar, LV_SIZE_CONTENT);   /// 6
lv_obj_set_align( ui_img_mv_bar, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_mv_bar, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_mv_bar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_mv_bar_knob = lv_img_create(ui_Cont_mV_bar);
lv_img_set_src(ui_img_mv_bar_knob, &ui_img_images_mv_bar_knob_png);
lv_obj_set_width( ui_img_mv_bar_knob, LV_SIZE_CONTENT);  /// 174
lv_obj_set_height( ui_img_mv_bar_knob, LV_SIZE_CONTENT);   /// 14
lv_obj_set_x( ui_img_mv_bar_knob, 0 );
lv_obj_set_y( ui_img_mv_bar_knob, -1 );
lv_obj_set_align( ui_img_mv_bar_knob, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_mv_bar_knob, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_mv_bar_knob, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Cont_TP = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Cont_TP);
lv_obj_set_width( ui_Cont_TP, 115);
lv_obj_set_height( ui_Cont_TP, 31);
lv_obj_set_x( ui_Cont_TP, -29 );
lv_obj_set_y( ui_Cont_TP, 28 );
lv_obj_set_align( ui_Cont_TP, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Cont_TP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_TP = lv_label_create(ui_Cont_TP);
lv_obj_set_width( ui_Label_TP, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_TP, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_TP, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_TP,"00,00");
lv_obj_set_style_text_color(ui_Label_TP, lv_color_hex(0x9CF486), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_TP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_TP, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_TP, &ui_font_Be30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_TP1 = lv_label_create(ui_Cont_TP);
lv_obj_set_width( ui_Label_TP1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_TP1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_TP1, 54 );
lv_obj_set_y( ui_Label_TP1, -1 );
lv_obj_set_align( ui_Label_TP1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_TP1,"TODAY\nPRODUCTION");
lv_obj_set_style_text_color(ui_Label_TP1, lv_color_hex(0x9CF486), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_TP1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_TP1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_TP1, -4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_TP1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_TP1, &ui_font_Be13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label_TP1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label_TP1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label_TP1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label_TP1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cont_CH = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Cont_CH);
lv_obj_set_width( ui_Cont_CH, 123);
lv_obj_set_height( ui_Cont_CH, 31);
lv_obj_set_x( ui_Cont_CH, 91 );
lv_obj_set_y( ui_Cont_CH, 28 );
lv_obj_set_align( ui_Cont_CH, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Cont_CH, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_CH = lv_label_create(ui_Cont_CH);
lv_obj_set_width( ui_Label_CH, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_CH, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_CH, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_CH,"0");
lv_obj_set_style_text_color(ui_Label_CH, lv_color_hex(0xFB6464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_CH, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_CH, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_CH, &ui_font_Be30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_CH1 = lv_label_create(ui_Cont_CH);
lv_obj_set_width( ui_Label_CH1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_CH1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_CH1, 54 );
lv_obj_set_y( ui_Label_CH1, -2 );
lv_obj_set_align( ui_Label_CH1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_CH1,"CONSUMPTION\nHOME");
lv_obj_set_style_text_color(ui_Label_CH1, lv_color_hex(0xFB6464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_CH1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_CH1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_CH1, -4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_CH1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_CH1, &ui_font_Be13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label_CH1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label_CH1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label_CH1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label_CH1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cont_CA = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Cont_CA);
lv_obj_set_width( ui_Cont_CA, 123);
lv_obj_set_height( ui_Cont_CA, 31);
lv_obj_set_x( ui_Cont_CA, 91 );
lv_obj_set_y( ui_Cont_CA, 60 );
lv_obj_set_align( ui_Cont_CA, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Cont_CA, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_CA = lv_label_create(ui_Cont_CA);
lv_obj_set_width( ui_Label_CA, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_CA, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_CA, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_CA,"0");
lv_obj_set_style_text_color(ui_Label_CA, lv_color_hex(0xFB6464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_CA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_CA, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_CA, &ui_font_Be30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_CA1 = lv_label_create(ui_Cont_CA);
lv_obj_set_width( ui_Label_CA1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_CA1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_CA1, 54 );
lv_obj_set_y( ui_Label_CA1, -2 );
lv_obj_set_align( ui_Label_CA1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_CA1,"CONSUMPTION\nAPPLIANCE");
lv_obj_set_style_text_color(ui_Label_CA1, lv_color_hex(0xFB6464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_CA1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_CA1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_CA1, -4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_CA1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_CA1, &ui_font_Be13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label_CA1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label_CA1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label_CA1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label_CA1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cont_Bat_label = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Cont_Bat_label);
lv_obj_set_width( ui_Cont_Bat_label, 64);
lv_obj_set_height( ui_Cont_Bat_label, 31);
lv_obj_set_x( ui_Cont_Bat_label, 4 );
lv_obj_set_y( ui_Cont_Bat_label, 18 );
lv_obj_set_align( ui_Cont_Bat_label, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(ui_Cont_Bat_label,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Cont_Bat_label, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Cont_Bat_label, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_bat = lv_label_create(ui_Cont_Bat_label);
lv_obj_set_width( ui_Label_bat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_bat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_bat, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_bat,"0");
lv_obj_set_style_text_color(ui_Label_bat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_bat, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_bat, &ui_font_Be30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Per = lv_label_create(ui_Cont_Bat_label);
lv_obj_set_width( ui_Label_Per, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Per, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Per, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Per,"%");
lv_obj_set_style_text_color(ui_Label_Per, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Per, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Per, &ui_font_Be13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label_Per, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label_Per, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label_Per, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label_Per, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cont_mV_label = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Cont_mV_label);
lv_obj_set_width( ui_Cont_mV_label, 76);
lv_obj_set_height( ui_Cont_mV_label, 31);
lv_obj_set_x( ui_Cont_mV_label, 4 );
lv_obj_set_y( ui_Cont_mV_label, 58 );
lv_obj_set_align( ui_Cont_mV_label, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(ui_Cont_mV_label,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Cont_mV_label, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Cont_mV_label, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_mV = lv_label_create(ui_Cont_mV_label);
lv_obj_set_width( ui_Label_mV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_mV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_mV, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_mV,"0");
lv_obj_set_style_text_color(ui_Label_mV, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_mV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_mV, &ui_font_Be30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_mV1 = lv_label_create(ui_Cont_mV_label);
lv_obj_set_width( ui_Label_mV1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_mV1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_mV1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_mV1,"mV\nDIFFERENCE");
lv_obj_set_style_text_color(ui_Label_mV1, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_mV1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_mV1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_mV1, -4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_mV1, &ui_font_Be13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label_mV1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label_mV1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label_mV1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label_mV1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

}
