// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: HA dashboard

#ifndef _HA_DASHBOARD_UI_H
#define _HA_DASHBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void in_Animation( lv_obj_t *TargetObject, int delay);
void out_Animation( lv_obj_t *TargetObject, int delay);
void blink_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image_sliderbg;
extern lv_obj_t *ui_Image_sliderknob;
extern lv_obj_t *ui_mask1;
extern lv_obj_t *ui_Image_bg;
extern lv_obj_t *ui_Container_ac;
extern lv_obj_t *ui_Image_wind;
extern lv_obj_t *ui_Image_ac;
extern lv_obj_t *ui_Container_lamp;
extern lv_obj_t *ui_Image_lamp;
extern lv_obj_t *ui_Image_lux;
extern lv_obj_t *ui_Container_blind;
extern lv_obj_t *ui_mask3;
extern lv_obj_t *ui_Image_ea;
extern lv_obj_t *ui_Image_blindpos;
extern lv_obj_t *ui_mask2;
extern lv_obj_t *ui_Image_blind;
extern lv_obj_t *ui_Container_icons;
extern lv_obj_t *ui_Image_iconactive;
extern lv_obj_t *ui_icon_ac;
extern lv_obj_t *ui_icon_lamp;
extern lv_obj_t *ui_icon_blind;
extern lv_obj_t *ui_label_set_value;
extern lv_obj_t *ui_label_set_unit;
extern lv_obj_t *ui_label_set_;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_img_slider_bg_png);   // assets/img/slider_bg.png
LV_IMG_DECLARE( ui_img_img_slider_knob_png);   // assets/img/slider_knob.png
LV_IMG_DECLARE( ui_img_img_bg_png);   // assets/img/bg.png
LV_IMG_DECLARE( ui_img_img_ac_wind_png);   // assets/img/ac_wind.png
LV_IMG_DECLARE( ui_img_img_ac_png);   // assets/img/ac.png
LV_IMG_DECLARE( ui_img_img_lamp_png);   // assets/img/lamp.png
LV_IMG_DECLARE( ui_img_img_lamp_lux_png);   // assets/img/lamp_lux.png
LV_IMG_DECLARE( ui_img_2024126593);   // assets/img/ea-01.png
LV_IMG_DECLARE( ui_img_img_blind_pos_png);   // assets/img/blind_pos.png
LV_IMG_DECLARE( ui_img_img_blind_png);   // assets/img/blind.png
LV_IMG_DECLARE( ui_img_img_icon_active_png);   // assets/img/icon_active.png
LV_IMG_DECLARE( ui_img_img_icon_ac_png);   // assets/img/icon_ac.png
LV_IMG_DECLARE( ui_img_img_icon_lamp_png);   // assets/img/icon_lamp.png
LV_IMG_DECLARE( ui_img_img_icon_blind_png);   // assets/img/icon_blind.png


LV_FONT_DECLARE( ui_font_be30);
LV_FONT_DECLARE( ui_font_be55);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
