// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: TD Nixie

#ifndef _TD_NIXIE_UI_H
#define _TD_NIXIE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_num_0;
extern lv_obj_t *ui_num_00;
extern lv_obj_t *ui_num_000;
extern lv_obj_t *ui_num_0000;
extern lv_obj_t *ui_num_1;
extern lv_obj_t *ui_num_2;
extern lv_obj_t *ui_num_3;
extern lv_obj_t *ui_num_4;
extern lv_obj_t *ui_num_5;
extern lv_obj_t *ui_num_6;
extern lv_obj_t *ui_num_7;
extern lv_obj_t *ui_num_8;
extern lv_obj_t *ui_num_9;
extern lv_obj_t *ui_img_bg;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_numbers_0_png);   // assets/numbers/0.png
LV_IMG_DECLARE( ui_img_numbers_1_png);   // assets/numbers/1.png
LV_IMG_DECLARE( ui_img_numbers_2_png);   // assets/numbers/2.png
LV_IMG_DECLARE( ui_img_numbers_3_png);   // assets/numbers/3.png
LV_IMG_DECLARE( ui_img_numbers_4_png);   // assets/numbers/4.png
LV_IMG_DECLARE( ui_img_numbers_5_png);   // assets/numbers/5.png
LV_IMG_DECLARE( ui_img_numbers_6_png);   // assets/numbers/6.png
LV_IMG_DECLARE( ui_img_numbers_7_png);   // assets/numbers/7.png
LV_IMG_DECLARE( ui_img_numbers_8_png);   // assets/numbers/8.png
LV_IMG_DECLARE( ui_img_numbers_9_png);   // assets/numbers/9.png
LV_IMG_DECLARE( ui_img_nixie_bg_png);   // assets/nixie bg.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
