// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Honda Watch

#ifndef _HONDA_WATCH_UI_H
#define _HONDA_WATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void speed_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image_bg;
extern lv_obj_t *ui_Panel_SL;
extern lv_obj_t *ui_Panel_SR;
extern lv_obj_t *ui_Label_speed;
extern lv_obj_t *ui_Image_needle_1;
extern lv_obj_t *ui_Image_needle_2;
extern lv_obj_t *ui_Image_icon;
extern lv_obj_t *ui_Label_main;
extern lv_obj_t *ui_Label_gear;
extern lv_obj_t *ui_Image_Speed;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_images_bg_png);   // assets/Images/bg.png
LV_IMG_DECLARE( ui_img_146392383);   // assets/Images/needle-1.png
LV_IMG_DECLARE( ui_img_581689746);   // assets/Images/needle-2.png
LV_IMG_DECLARE( ui_img_images_icon_png);   // assets/Images/icon.png
LV_IMG_DECLARE( ui_img_1963052260);   // assets/Images/Anim/speed-00.png
LV_IMG_DECLARE( ui_img_1963053285);   // assets/Images/Anim/speed-01.png
LV_IMG_DECLARE( ui_img_1963050210);   // assets/Images/Anim/speed-02.png
LV_IMG_DECLARE( ui_img_1963051235);   // assets/Images/Anim/speed-03.png
LV_IMG_DECLARE( ui_img_1963047912);   // assets/Images/Anim/speed-04.png
LV_IMG_DECLARE( ui_img_1963048937);   // assets/Images/Anim/speed-05.png
LV_IMG_DECLARE( ui_img_1963045862);   // assets/Images/Anim/speed-06.png
LV_IMG_DECLARE( ui_img_1963046887);   // assets/Images/Anim/speed-07.png
LV_IMG_DECLARE( ui_img_1963060972);   // assets/Images/Anim/speed-08.png
LV_IMG_DECLARE( ui_img_1963061997);   // assets/Images/Anim/speed-09.png
LV_IMG_DECLARE( ui_img_1524054327);   // assets/Images/Anim/speed-10.png
LV_IMG_DECLARE( ui_img_1524053302);   // assets/Images/Anim/speed-11.png
LV_IMG_DECLARE( ui_img_1524056377);   // assets/Images/Anim/speed-12.png

// FONTS
LV_FONT_DECLARE( ui_font_BR12);
LV_FONT_DECLARE( ui_font_BR25);
LV_FONT_DECLARE( ui_font_DS18);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
