// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: bot

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_blink = lv_img_create(ui_Screen1);
lv_img_set_src(ui_blink, &ui_img_440651951);
lv_obj_set_width( ui_blink, 190);
lv_obj_set_height( ui_blink, 110);
lv_obj_set_x( ui_blink, 65 );
lv_obj_set_y( ui_blink, 25 );
lv_obj_add_flag( ui_blink, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_blink, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_angry = lv_img_create(ui_Screen1);
lv_img_set_src(ui_angry, &ui_img_440651951);
lv_obj_set_width( ui_angry, 190);
lv_obj_set_height( ui_angry, 110);
lv_obj_set_x( ui_angry, 65 );
lv_obj_set_y( ui_angry, 25 );
lv_obj_add_flag( ui_angry, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_angry, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_love = lv_img_create(ui_Screen1);
lv_img_set_src(ui_love, &ui_img_440651951);
lv_obj_set_width( ui_love, 190);
lv_obj_set_height( ui_love, 110);
lv_obj_set_x( ui_love, 65 );
lv_obj_set_y( ui_love, 25 );
lv_obj_add_flag( ui_love, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_love, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_sad = lv_img_create(ui_Screen1);
lv_img_set_src(ui_sad, &ui_img_440651951);
lv_obj_set_width( ui_sad, 190);
lv_obj_set_height( ui_sad, 110);
lv_obj_set_x( ui_sad, 65 );
lv_obj_set_y( ui_sad, 25 );
lv_obj_add_flag( ui_sad, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_sad, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_sleepy = lv_img_create(ui_Screen1);
lv_img_set_src(ui_sleepy, &ui_img_440651951);
lv_obj_set_width( ui_sleepy, 190);
lv_obj_set_height( ui_sleepy, 110);
lv_obj_set_x( ui_sleepy, 65 );
lv_obj_set_y( ui_sleepy, 25 );
lv_obj_add_flag( ui_sleepy, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_sleepy, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_awe = lv_img_create(ui_Screen1);
lv_img_set_src(ui_awe, &ui_img_440651951);
lv_obj_set_width( ui_awe, 190);
lv_obj_set_height( ui_awe, 110);
lv_obj_set_x( ui_awe, 65 );
lv_obj_set_y( ui_awe, 25 );
lv_obj_add_flag( ui_awe, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_awe, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
