// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Attitude indicator

#ifndef _ATTITUDE_INDICATOR_UI_H
#define _ATTITUDE_INDICATOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_img_dial_bg;
extern lv_obj_t *ui_img_pitch_scale;
extern lv_obj_t *ui_img_roll_scale;
extern lv_obj_t *ui_img_mask;
extern lv_obj_t *ui_img_dial;
extern lv_obj_t *ui_img_pointer;
extern lv_obj_t *ui_Label_roll;
extern lv_obj_t *ui_Label__pitch;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_images_dial_bg_png);   // assets/Images/Dial bg.png
LV_IMG_DECLARE( ui_img_images_pitch_scale_png);   // assets/Images/Pitch Scale.png
LV_IMG_DECLARE( ui_img_images_roll_scale_png);   // assets/Images/Roll Scale.png
LV_IMG_DECLARE( ui_img_images_mask_png);   // assets/Images/Mask.png
LV_IMG_DECLARE( ui_img_images_dial_png);   // assets/Images/Dial.png
LV_IMG_DECLARE( ui_img_images_pointer_png);   // assets/Images/Pointer.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
