// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Honda Watch

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_bg = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_bg, &ui_img_images_bg_png);
lv_obj_set_width( ui_Image_bg, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_Image_bg, LV_SIZE_CONTENT);   /// 170
lv_obj_set_align( ui_Image_bg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_bg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel_SL = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel_SL, 56);
lv_obj_set_height( ui_Panel_SL, 27);
lv_obj_set_x( ui_Panel_SL, -128 );
lv_obj_set_y( ui_Panel_SL, -61 );
lv_obj_set_align( ui_Panel_SL, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel_SL, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel_SL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel_SL, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_SL, 210, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel_SL, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel_SL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel_SL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_Panel_SL, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel_SR = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel_SR, 56);
lv_obj_set_height( ui_Panel_SR, 27);
lv_obj_set_x( ui_Panel_SR, 128 );
lv_obj_set_y( ui_Panel_SR, -62 );
lv_obj_set_align( ui_Panel_SR, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel_SR, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel_SR, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel_SR, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_SR, 210, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel_SR, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel_SR, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel_SR, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_Panel_SR, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_speed = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label_speed, 50);
lv_obj_set_height( ui_Label_speed, 18);
lv_obj_set_x( ui_Label_speed, 0 );
lv_obj_set_y( ui_Label_speed, 61 );
lv_obj_set_align( ui_Label_speed, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_speed,"80");
lv_obj_set_style_text_color(ui_Label_speed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_speed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_speed, &ui_font_DS18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_needle_1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_needle_1, &ui_img_146392383);
lv_obj_set_width( ui_Image_needle_1, LV_SIZE_CONTENT);  /// 6
lv_obj_set_height( ui_Image_needle_1, LV_SIZE_CONTENT);   /// 135
lv_obj_set_x( ui_Image_needle_1, 188 );
lv_obj_set_y( ui_Image_needle_1, 47 );
lv_obj_add_flag( ui_Image_needle_1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_needle_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_Image_needle_1,3,135);
lv_img_set_angle(ui_Image_needle_1,400);

ui_Image_needle_2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_needle_2, &ui_img_581689746);
lv_obj_set_width( ui_Image_needle_2, LV_SIZE_CONTENT);  /// 5
lv_obj_set_height( ui_Image_needle_2, LV_SIZE_CONTENT);   /// 38
lv_obj_set_x( ui_Image_needle_2, 257 );
lv_obj_set_y( ui_Image_needle_2, 139 );
lv_obj_add_flag( ui_Image_needle_2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_needle_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_Image_needle_2,2,38);
lv_img_set_angle(ui_Image_needle_2,500);

ui_Image_icon = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_icon, &ui_img_images_icon_png);
lv_obj_set_width( ui_Image_icon, LV_SIZE_CONTENT);  /// 36
lv_obj_set_height( ui_Image_icon, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_Image_icon, -63 );
lv_obj_set_y( ui_Image_icon, -61 );
lv_obj_set_align( ui_Image_icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_main = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label_main, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_main, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_main, 0 );
lv_obj_set_y( ui_Label_main, -63 );
lv_obj_set_align( ui_Label_main, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_main,"TOP\nGEAR");
lv_obj_set_style_text_color(ui_Label_main, lv_color_hex(0xA4D730), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_main, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_main, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_main, -5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_main, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_main, &ui_font_BR12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_gear = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label_gear, 28);
lv_obj_set_height( ui_Label_gear, 21);
lv_obj_set_x( ui_Label_gear, 66 );
lv_obj_set_y( ui_Label_gear, -64 );
lv_obj_set_align( ui_Label_gear, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_gear,"N");
lv_obj_set_style_text_align(ui_Label_gear, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_gear, &ui_font_BR25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_Speed = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_Speed, &ui_img_1963052260);
lv_obj_set_width( ui_Image_Speed, LV_SIZE_CONTENT);  /// 272
lv_obj_set_height( ui_Image_Speed, LV_SIZE_CONTENT);   /// 94
lv_obj_set_x( ui_Image_Speed, -4 );
lv_obj_set_y( ui_Image_Speed, 21 );
lv_obj_set_align( ui_Image_Speed, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_Speed, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_Speed, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_opa(ui_Image_Speed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_Image_Speed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}
