// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: compass

#ifndef _COMPASS_UI_H
#define _COMPASS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void Compass_test_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_compass;
extern lv_obj_t *ui_overlay;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_lbl_degree;
extern lv_obj_t *ui_lbl_direction;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_indicator;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_compass_png);   // assets/compass.png
LV_IMG_DECLARE( ui_img_overlay_png);   // assets/Overlay.png
LV_IMG_DECLARE( ui_img_indicator_1_png);   // assets/Indicator_1.png


LV_FONT_DECLARE( ui_font_Mo14);
LV_FONT_DECLARE( ui_font_Mo40);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
