// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Digital Pricetag

#include "../ui.h"

void ui_screen_tag_screen_init(void)
{
ui_screen_tag = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_tag, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_product = lv_label_create(ui_screen_tag);
lv_obj_set_width( ui_Label_product, 320);
lv_obj_set_height( ui_Label_product, 60);
lv_label_set_text(ui_Label_product,"-");
lv_obj_set_style_text_letter_space(ui_Label_product, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_product, -5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_product, &ui_font_g28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label_product, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label_product, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label_product, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label_product, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_screen_tag);
lv_obj_set_width( ui_Panel1, 320);
lv_obj_set_height( ui_Panel1, 2);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, -18 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_screen_tag);
lv_obj_set_width( ui_Panel2, 320);
lv_obj_set_height( ui_Panel2, 2);
lv_obj_set_x( ui_Panel2, 0 );
lv_obj_set_y( ui_Panel2, 53 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel_save = lv_obj_create(ui_screen_tag);
lv_obj_set_width( ui_Panel_save, 117);
lv_obj_set_height( ui_Panel_save, 103);
lv_obj_set_x( ui_Panel_save, 101 );
lv_obj_set_y( ui_Panel_save, 34 );
lv_obj_set_align( ui_Panel_save, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel_save, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel_save, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel_save, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_save, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel_save, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel_save, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_label_now_price = lv_label_create(ui_screen_tag);
lv_obj_set_width( ui_label_now_price, 196);
lv_obj_set_height( ui_label_now_price, 59);
lv_obj_set_x( ui_label_now_price, -59 );
lv_obj_set_y( ui_label_now_price, 15 );
lv_obj_set_align( ui_label_now_price, LV_ALIGN_CENTER );
lv_label_set_text(ui_label_now_price,"-");
lv_obj_set_style_text_color(ui_label_now_price, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_label_now_price, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_label_now_price, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label_now_price, &ui_font_g60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_label_was_price = lv_label_create(ui_screen_tag);
lv_obj_set_width( ui_label_was_price, 111);
lv_obj_set_height( ui_label_was_price, 35);
lv_obj_set_x( ui_label_was_price, 101 );
lv_obj_set_y( ui_label_was_price, 67 );
lv_obj_set_align( ui_label_was_price, LV_ALIGN_CENTER );
lv_label_set_text(ui_label_was_price,"-");
lv_obj_set_style_text_color(ui_label_was_price, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_label_was_price, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_label_was_price, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_label_was_price, LV_TEXT_DECOR_STRIKETHROUGH, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label_was_price, &ui_font_g26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_label_save_value = lv_label_create(ui_screen_tag);
lv_obj_set_width( ui_label_save_value, 72);
lv_obj_set_height( ui_label_save_value, 55);
lv_obj_set_x( ui_label_save_value, 88 );
lv_obj_set_y( ui_label_save_value, 25 );
lv_obj_set_align( ui_label_save_value, LV_ALIGN_CENTER );
lv_label_set_text(ui_label_save_value,"-");
lv_obj_set_style_text_color(ui_label_save_value, lv_color_hex(0xE3FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_label_save_value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_label_save_value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label_save_value, &ui_font_g50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_label_per = lv_label_create(ui_screen_tag);
lv_obj_set_width( ui_label_per, 24);
lv_obj_set_height( ui_label_per, 35);
lv_obj_set_x( ui_label_per, 141 );
lv_obj_set_y( ui_label_per, 22 );
lv_obj_set_align( ui_label_per, LV_ALIGN_CENTER );
lv_label_set_text(ui_label_per,"%");
lv_obj_set_style_text_color(ui_label_per, lv_color_hex(0xE3FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_label_per, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_label_per, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label_per, &ui_font_g28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_label_save = lv_label_create(ui_screen_tag);
lv_obj_set_width( ui_label_save, 90);
lv_obj_set_height( ui_label_save, 20);
lv_obj_set_x( ui_label_save, 106 );
lv_obj_set_y( ui_label_save, -8 );
lv_obj_set_align( ui_label_save, LV_ALIGN_CENTER );
lv_label_set_text(ui_label_save,"SAVE");
lv_obj_set_style_text_color(ui_label_save, lv_color_hex(0xE3FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_label_save, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_label_save, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label_save, &ui_font_g22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_barcode = lv_img_create(ui_screen_tag);
lv_img_set_src(ui_img_barcode, &ui_img_img_code_png);
lv_obj_set_width( ui_img_barcode, LV_SIZE_CONTENT);  /// 118
lv_obj_set_height( ui_img_barcode, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_img_barcode, -58 );
lv_obj_set_y( ui_img_barcode, 69 );
lv_obj_set_align( ui_img_barcode, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_barcode, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_barcode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
