// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Digital Pricetag

#include "../ui.h"

void ui_screen_wifi_screen_init(void)
{
ui_screen_wifi = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_wifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Img_wifi = lv_img_create(ui_screen_wifi);
lv_img_set_src(ui_Img_wifi, &ui_img_wifi_icon_wifi_1_png);
lv_obj_set_width( ui_Img_wifi, LV_SIZE_CONTENT);  /// 62
lv_obj_set_height( ui_Img_wifi, LV_SIZE_CONTENT);   /// 62
lv_obj_set_x( ui_Img_wifi, 0 );
lv_obj_set_y( ui_Img_wifi, -15 );
lv_obj_set_align( ui_Img_wifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Img_wifi, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Img_wifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_wifi = lv_label_create(ui_screen_wifi);
lv_obj_set_width( ui_Label_wifi, 171);
lv_obj_set_height( ui_Label_wifi, 25);
lv_obj_set_x( ui_Label_wifi, 78 );
lv_obj_set_y( ui_Label_wifi, 110 );
lv_label_set_text(ui_Label_wifi,"Connecting...");
lv_obj_set_style_text_align(ui_Label_wifi, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_wifi, &ui_font_g22, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_screen_wifi, ui_event_screen_wifi, LV_EVENT_ALL, NULL);

}
