// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: td world clock

#ifndef _TD_WORLD_CLOCK_UI_H
#define _TD_WORLD_CLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void imgloc_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel_map;
extern lv_obj_t *ui_img_map_bg;
extern lv_obj_t *ui_img_map_bg_blue;
extern lv_obj_t *ui_img_world_map;
extern lv_obj_t *ui_Label_cc_a;
extern lv_obj_t *ui_Panel_local_time;
extern lv_obj_t *ui_img_local_time;
extern lv_obj_t *ui_img_local_time_blue;
extern lv_obj_t *ui_Label_lt_b;
extern lv_obj_t *ui_Label_lt_a;
extern lv_obj_t *ui_Label_lt_ampm;
extern lv_obj_t *ui_Panel_world_time;
extern lv_obj_t *ui_img_world_time;
extern lv_obj_t *ui_img_world_time_blue;
extern lv_obj_t *ui_Label_wt_b;
extern lv_obj_t *ui_Label_wt_a;
extern lv_obj_t *ui_Label_cc;
extern lv_obj_t *ui_Label_gmt;
extern lv_obj_t *ui_Label_wt_ampm;
extern lv_obj_t *ui_Label_wt_sec_b;
extern lv_obj_t *ui_Label_wt_sec_a;
extern lv_obj_t *ui_img_loc;
extern lv_obj_t *ui_action_1;
extern lv_obj_t *ui_action_2;
extern lv_obj_t *ui_action_3;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_map_image_s_png);   // assets/map_image_s.png
LV_IMG_DECLARE( ui_img_map_image_blue_png);   // assets/map_image_blue.png
LV_IMG_DECLARE( ui_img_world_map_png);   // assets/world_map.png
LV_IMG_DECLARE( ui_img_current_time_s_png);   // assets/current_time_s.png
LV_IMG_DECLARE( ui_img_current_time_blue_png);   // assets/current_time_blue.png
LV_IMG_DECLARE( ui_img_world_time_s_png);   // assets/world_time_s.png
LV_IMG_DECLARE( ui_img_world_time_blue_png);   // assets/world_time_blue.png
LV_IMG_DECLARE( ui_img_loc_png);   // assets/loc.png

LV_FONT_DECLARE( ui_font_ds12);
LV_FONT_DECLARE( ui_font_ds16);
LV_FONT_DECLARE( ui_font_ds20);
LV_FONT_DECLARE( ui_font_ds29);
LV_FONT_DECLARE( ui_font_ds60);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
