// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: HA dashboard

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x1B0B3E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_sliderbg = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_sliderbg, &ui_img_img_slider_bg_png);
lv_obj_set_width( ui_Image_sliderbg, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_Image_sliderbg, LV_SIZE_CONTENT);   /// 88
lv_obj_set_x( ui_Image_sliderbg, -125 );
lv_obj_set_y( ui_Image_sliderbg, -12 );
lv_obj_set_align( ui_Image_sliderbg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_sliderbg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_sliderbg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_sliderknob = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_sliderknob, &ui_img_img_slider_knob_png);
lv_obj_set_width( ui_Image_sliderknob, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_Image_sliderknob, LV_SIZE_CONTENT);   /// 93
lv_obj_set_x( ui_Image_sliderknob, 20 );
lv_obj_set_y( ui_Image_sliderknob, 110 );
lv_obj_add_flag( ui_Image_sliderknob, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_sliderknob, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mask1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_mask1, 35);
lv_obj_set_height( ui_mask1, 50);
lv_obj_set_x( ui_mask1, -125 );
lv_obj_set_y( ui_mask1, 61 );
lv_obj_set_align( ui_mask1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_mask1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_mask1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mask1, lv_color_hex(0x180839), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mask1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_mask1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_mask1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_bg = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_bg, &ui_img_img_bg_png);
lv_obj_set_width( ui_Image_bg, LV_SIZE_CONTENT);  /// 295
lv_obj_set_height( ui_Image_bg, LV_SIZE_CONTENT);   /// 105
lv_obj_set_x( ui_Image_bg, 12 );
lv_obj_set_y( ui_Image_bg, 22 );
lv_obj_add_flag( ui_Image_bg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container_ac = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_ac);
lv_obj_set_width( ui_Container_ac, 244);
lv_obj_set_height( ui_Container_ac, 170);
lv_obj_set_x( ui_Container_ac, 0 );
lv_obj_set_y( ui_Container_ac, -200 );
lv_obj_set_align( ui_Container_ac, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Container_ac, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_wind = lv_img_create(ui_Container_ac);
lv_img_set_src(ui_Image_wind, &ui_img_img_ac_wind_png);
lv_obj_set_width( ui_Image_wind, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image_wind, LV_SIZE_CONTENT);   /// 81
lv_obj_set_x( ui_Image_wind, 75 );
lv_obj_set_y( ui_Image_wind, -5 );
lv_obj_set_align( ui_Image_wind, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_wind, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_wind, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_ac = lv_img_create(ui_Container_ac);
lv_img_set_src(ui_Image_ac, &ui_img_img_ac_png);
lv_obj_set_width( ui_Image_ac, LV_SIZE_CONTENT);  /// 244
lv_obj_set_height( ui_Image_ac, LV_SIZE_CONTENT);   /// 96
lv_obj_set_x( ui_Image_ac, 80 );
lv_obj_set_y( ui_Image_ac, -30 );
lv_obj_set_align( ui_Image_ac, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_ac, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_ac, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container_lamp = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_lamp);
lv_obj_set_width( ui_Container_lamp, 244);
lv_obj_set_height( ui_Container_lamp, 170);
lv_obj_set_x( ui_Container_lamp, 0 );
lv_obj_set_y( ui_Container_lamp, -200 );
lv_obj_set_align( ui_Container_lamp, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Container_lamp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_lamp = lv_img_create(ui_Container_lamp);
lv_img_set_src(ui_Image_lamp, &ui_img_img_lamp_png);
lv_obj_set_width( ui_Image_lamp, LV_SIZE_CONTENT);  /// 244
lv_obj_set_height( ui_Image_lamp, LV_SIZE_CONTENT);   /// 96
lv_obj_set_x( ui_Image_lamp, 30 );
lv_obj_set_y( ui_Image_lamp, -30 );
lv_obj_set_align( ui_Image_lamp, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_lamp, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_lamp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_lux = lv_img_create(ui_Container_lamp);
lv_img_set_src(ui_Image_lux, &ui_img_img_lamp_lux_png);
lv_obj_set_width( ui_Image_lux, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image_lux, LV_SIZE_CONTENT);   /// 81
lv_obj_set_x( ui_Image_lux, 25 );
lv_obj_set_y( ui_Image_lux, 55 );
lv_obj_set_align( ui_Image_lux, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_lux, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_lux, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container_blind = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_blind);
lv_obj_set_width( ui_Container_blind, 244);
lv_obj_set_height( ui_Container_blind, 170);
lv_obj_set_x( ui_Container_blind, 0 );
lv_obj_set_y( ui_Container_blind, -200 );
lv_obj_set_align( ui_Container_blind, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Container_blind, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mask3 = lv_obj_create(ui_Container_blind);
lv_obj_set_width( ui_mask3, 81);
lv_obj_set_height( ui_mask3, 137);
lv_obj_set_x( ui_mask3, 32 );
lv_obj_set_y( ui_mask3, -6 );
lv_obj_set_align( ui_mask3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_mask3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_mask3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mask3, lv_color_hex(0x180839), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mask3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_mask3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_mask3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_ea = lv_img_create(ui_Container_blind);
lv_img_set_src(ui_Image_ea, &ui_img_2024126593);
lv_obj_set_width( ui_Image_ea, LV_SIZE_CONTENT);  /// 45
lv_obj_set_height( ui_Image_ea, LV_SIZE_CONTENT);   /// 37
lv_obj_set_x( ui_Image_ea, 31 );
lv_obj_set_y( ui_Image_ea, -10 );
lv_obj_set_align( ui_Image_ea, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_ea, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_ea, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_blindpos = lv_img_create(ui_Container_blind);
lv_img_set_src(ui_Image_blindpos, &ui_img_img_blind_pos_png);
lv_obj_set_width( ui_Image_blindpos, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image_blindpos, LV_SIZE_CONTENT);   /// 81
lv_obj_set_x( ui_Image_blindpos, 28 );
lv_obj_set_y( ui_Image_blindpos, -10 );
lv_obj_set_align( ui_Image_blindpos, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_blindpos, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_blindpos, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mask2 = lv_obj_create(ui_Container_blind);
lv_obj_set_width( ui_mask2, 139);
lv_obj_set_height( ui_mask2, 21);
lv_obj_set_x( ui_mask2, 37 );
lv_obj_set_y( ui_mask2, -89 );
lv_obj_set_align( ui_mask2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_mask2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_mask2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mask2, lv_color_hex(0x180839), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mask2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_mask2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_mask2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_blind = lv_img_create(ui_Container_blind);
lv_img_set_src(ui_Image_blind, &ui_img_img_blind_png);
lv_obj_set_width( ui_Image_blind, LV_SIZE_CONTENT);  /// 244
lv_obj_set_height( ui_Image_blind, LV_SIZE_CONTENT);   /// 96
lv_obj_set_x( ui_Image_blind, 31 );
lv_obj_set_y( ui_Image_blind, -10 );
lv_obj_set_align( ui_Image_blind, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_blind, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_blind, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container_icons = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_icons);
lv_obj_set_width( ui_Container_icons, 138);
lv_obj_set_height( ui_Container_icons, 43);
lv_obj_set_x( ui_Container_icons, 29 );
lv_obj_set_y( ui_Container_icons, 123 );
lv_obj_clear_flag( ui_Container_icons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_iconactive = lv_img_create(ui_Container_icons);
lv_img_set_src(ui_Image_iconactive, &ui_img_img_icon_active_png);
lv_obj_set_width( ui_Image_iconactive, LV_SIZE_CONTENT);  /// 58
lv_obj_set_height( ui_Image_iconactive, LV_SIZE_CONTENT);   /// 42
lv_obj_add_flag( ui_Image_iconactive, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_iconactive, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icon_ac = lv_img_create(ui_Container_icons);
lv_img_set_src(ui_icon_ac, &ui_img_img_icon_ac_png);
lv_obj_set_width( ui_icon_ac, LV_SIZE_CONTENT);  /// 23
lv_obj_set_height( ui_icon_ac, LV_SIZE_CONTENT);   /// 25
lv_obj_set_x( ui_icon_ac, 17 );
lv_obj_set_y( ui_icon_ac, 15 );
lv_obj_add_flag( ui_icon_ac, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_ac, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_icon_ac, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_icon_ac, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icon_lamp = lv_img_create(ui_Container_icons);
lv_img_set_src(ui_icon_lamp, &ui_img_img_icon_lamp_png);
lv_obj_set_width( ui_icon_lamp, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_icon_lamp, LV_SIZE_CONTENT);   /// 25
lv_obj_set_x( ui_icon_lamp, 55 );
lv_obj_set_y( ui_icon_lamp, 15 );
lv_obj_add_flag( ui_icon_lamp, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_lamp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_icon_lamp, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_icon_lamp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icon_blind = lv_img_create(ui_Container_icons);
lv_img_set_src(ui_icon_blind, &ui_img_img_icon_blind_png);
lv_obj_set_width( ui_icon_blind, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_icon_blind, LV_SIZE_CONTENT);   /// 25
lv_obj_set_x( ui_icon_blind, 93 );
lv_obj_set_y( ui_icon_blind, 15 );
lv_obj_add_flag( ui_icon_blind, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_blind, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_icon_blind, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_icon_blind, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_label_set_value = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_label_set_value, 68);
lv_obj_set_height( ui_label_set_value, 52);
lv_obj_set_x( ui_label_set_value, -62 );
lv_obj_set_y( ui_label_set_value, -31 );
lv_obj_set_align( ui_label_set_value, LV_ALIGN_CENTER );
lv_label_set_text(ui_label_set_value,"25");
lv_obj_set_style_text_align(ui_label_set_value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label_set_value, &ui_font_be55, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_label_set_unit = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_label_set_unit, 29);
lv_obj_set_height( ui_label_set_unit, 29);
lv_obj_set_x( ui_label_set_unit, -12 );
lv_obj_set_y( ui_label_set_unit, -37 );
lv_obj_set_align( ui_label_set_unit, LV_ALIGN_CENTER );
lv_label_set_text(ui_label_set_unit,"°");
lv_obj_set_style_text_align(ui_label_set_unit, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label_set_unit, &ui_font_be30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_label_set_ = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_label_set_, 67);
lv_obj_set_height( ui_label_set_, 28);
lv_obj_set_x( ui_label_set_, -46 );
lv_obj_set_y( ui_label_set_, 12 );
lv_obj_set_align( ui_label_set_, LV_ALIGN_CENTER );
lv_label_set_text(ui_label_set_,"SET");
lv_obj_set_style_text_align(ui_label_set_, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label_set_, &ui_font_be30, LV_PART_MAIN| LV_STATE_DEFAULT);

}
