// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Calculator

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_bg = lv_img_create(ui_Screen1);
lv_img_set_src(ui_img_bg, &ui_img_1548360417);
lv_obj_set_width( ui_img_bg, LV_SIZE_CONTENT);  /// 170
lv_obj_set_height( ui_img_bg, LV_SIZE_CONTENT);   /// 320
lv_obj_set_align( ui_img_bg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_bg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_img_bg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_img_bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_img_bg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbl_title = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lbl_title, 127);
lv_obj_set_height( ui_lbl_title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbl_title, 15 );
lv_obj_set_y( ui_lbl_title, -139 );
lv_obj_set_align( ui_lbl_title, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbl_title,"Calculator");
lv_obj_set_style_text_align(ui_lbl_title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbl_title, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pnl_close = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_pnl_close, 18);
lv_obj_set_height( ui_pnl_close, 18);
lv_obj_set_x( ui_pnl_close, 11 );
lv_obj_set_y( ui_pnl_close, 13 );
lv_obj_clear_flag( ui_pnl_close, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_pnl_close, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_pnl_close, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnl_close, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_pnl_close, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_pnl_close, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_pnl_close, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_png_answer = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_png_answer, 155);
lv_obj_set_height( ui_png_answer, 35);
lv_obj_set_x( ui_png_answer, 6 );
lv_obj_set_y( ui_png_answer, 51 );
lv_obj_clear_flag( ui_png_answer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_png_answer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_png_answer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_png_answer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_png_answer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_png_answer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_png_answer, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_png_answer, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbl_answer = lv_label_create(ui_png_answer);
lv_obj_set_width( ui_lbl_answer, 139);
lv_obj_set_height( ui_lbl_answer, 18);
lv_obj_set_x( ui_lbl_answer, -8 );
lv_obj_set_y( ui_lbl_answer, -5 );
lv_label_set_text(ui_lbl_answer,"");
lv_obj_set_style_text_color(ui_lbl_answer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lbl_answer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lbl_answer, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbl_answer, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_pad_bg = lv_img_create(ui_Screen1);
lv_img_set_src(ui_img_pad_bg, &ui_img_pad_bg_png);
lv_obj_set_width( ui_img_pad_bg, LV_SIZE_CONTENT);  /// 151
lv_obj_set_height( ui_img_pad_bg, LV_SIZE_CONTENT);   /// 204
lv_obj_set_x( ui_img_pad_bg, 10 );
lv_obj_set_y( ui_img_pad_bg, 98 );
lv_obj_add_flag( ui_img_pad_bg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_pad_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_pad_c = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_c, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_c, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_c, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_c, 7 );
lv_obj_set_y( ui_pad_c, 95 );
lv_obj_add_flag( ui_pad_c, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_c, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_pad_c);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 11 );
lv_obj_set_y( ui_Label3, 7 );
lv_label_set_text(ui_Label3,"C");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_eql_s = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_eql_s, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_eql_s, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_eql_s, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_eql_s, 47 );
lv_obj_set_y( ui_pad_eql_s, 95 );
lv_obj_add_flag( ui_pad_eql_s, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_eql_s, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_pad_eql_s);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 11 );
lv_obj_set_y( ui_Label1, 7 );
lv_label_set_text(ui_Label1,"=");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_dev = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_dev, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_dev, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_dev, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_dev, 87 );
lv_obj_set_y( ui_pad_dev, 95 );
lv_obj_add_flag( ui_pad_dev, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_dev, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_pad_dev);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 11 );
lv_obj_set_y( ui_Label2, 7 );
lv_label_set_text(ui_Label2,"/");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_multy = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_multy, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_multy, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_multy, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_multy, 127 );
lv_obj_set_y( ui_pad_multy, 95 );
lv_obj_add_flag( ui_pad_multy, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_multy, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_pad_multy);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 11 );
lv_obj_set_y( ui_Label4, 7 );
lv_label_set_text(ui_Label4,"*");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_minus = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_minus, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_minus, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_minus, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_minus, 127 );
lv_obj_set_y( ui_pad_minus, 138 );
lv_obj_add_flag( ui_pad_minus, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_minus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_pad_minus);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 11 );
lv_obj_set_y( ui_Label5, 7 );
lv_label_set_text(ui_Label5,"-");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_9 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_9, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_9, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_9, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_9, 87 );
lv_obj_set_y( ui_pad_9, 138 );
lv_obj_add_flag( ui_pad_9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_pad_9);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 11 );
lv_obj_set_y( ui_Label6, 7 );
lv_label_set_text(ui_Label6,"9");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_8 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_8, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_8, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_8, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_8, 47 );
lv_obj_set_y( ui_pad_8, 138 );
lv_obj_add_flag( ui_pad_8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_pad_8);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 11 );
lv_obj_set_y( ui_Label7, 7 );
lv_label_set_text(ui_Label7,"8");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_7 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_7, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_7, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_7, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_7, 7 );
lv_obj_set_y( ui_pad_7, 138 );
lv_obj_add_flag( ui_pad_7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label8 = lv_label_create(ui_pad_7);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, 11 );
lv_obj_set_y( ui_Label8, 7 );
lv_label_set_text(ui_Label8,"7");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_4 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_4, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_4, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_4, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_4, 7 );
lv_obj_set_y( ui_pad_4, 182 );
lv_obj_add_flag( ui_pad_4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_pad_4);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 11 );
lv_obj_set_y( ui_Label9, 7 );
lv_label_set_text(ui_Label9,"4");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_5 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_5, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_5, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_5, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_5, 47 );
lv_obj_set_y( ui_pad_5, 182 );
lv_obj_add_flag( ui_pad_5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label10 = lv_label_create(ui_pad_5);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, 11 );
lv_obj_set_y( ui_Label10, 7 );
lv_label_set_text(ui_Label10,"5");
lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label10, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_6 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_6, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_6, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_6, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_6, 87 );
lv_obj_set_y( ui_pad_6, 182 );
lv_obj_add_flag( ui_pad_6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_pad_6);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, 11 );
lv_obj_set_y( ui_Label11, 7 );
lv_label_set_text(ui_Label11,"6");
lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_plus = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_plus, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_plus, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_plus, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_plus, 127 );
lv_obj_set_y( ui_pad_plus, 182 );
lv_obj_add_flag( ui_pad_plus, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_plus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label12 = lv_label_create(ui_pad_plus);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, 11 );
lv_obj_set_y( ui_Label12, 7 );
lv_label_set_text(ui_Label12,"+");
lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label12, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_1, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_1, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_1, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_1, 7 );
lv_obj_set_y( ui_pad_1, 226 );
lv_obj_add_flag( ui_pad_1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label13 = lv_label_create(ui_pad_1);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, 11 );
lv_obj_set_y( ui_Label13, 7 );
lv_label_set_text(ui_Label13,"1");
lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label13, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_2, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_2, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_2, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_2, 47 );
lv_obj_set_y( ui_pad_2, 226 );
lv_obj_add_flag( ui_pad_2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label14 = lv_label_create(ui_pad_2);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label14, 11 );
lv_obj_set_y( ui_Label14, 7 );
lv_label_set_text(ui_Label14,"2");
lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label14, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_3 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_3, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_3, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_3, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_3, 87 );
lv_obj_set_y( ui_pad_3, 226 );
lv_obj_add_flag( ui_pad_3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label15 = lv_label_create(ui_pad_3);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, 11 );
lv_obj_set_y( ui_Label15, 7 );
lv_label_set_text(ui_Label15,"3");
lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label15, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_eql_b = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_eql_b, &ui_img_pad_single_v_png);
lv_obj_set_width( ui_pad_eql_b, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_eql_b, LV_SIZE_CONTENT);   /// 72
lv_obj_set_x( ui_pad_eql_b, 127 );
lv_obj_set_y( ui_pad_eql_b, 226 );
lv_obj_add_flag( ui_pad_eql_b, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_eql_b, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label18 = lv_label_create(ui_pad_eql_b);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label18, 11 );
lv_obj_set_y( ui_Label18, 50 );
lv_label_set_text(ui_Label18,"=");
lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label18, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_0_b = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_0_b, &ui_img_pad_singl_h_png);
lv_obj_set_width( ui_pad_0_b, LV_SIZE_CONTENT);  /// 71
lv_obj_set_height( ui_pad_0_b, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_0_b, 8 );
lv_obj_set_y( ui_pad_0_b, 266 );
lv_obj_add_flag( ui_pad_0_b, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_0_b, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label17 = lv_label_create(ui_pad_0_b);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label17, 11 );
lv_obj_set_y( ui_Label17, 7 );
lv_label_set_text(ui_Label17,"0");
lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label17, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pad_dot = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pad_dot, &ui_img_pad_single_png);
lv_obj_set_width( ui_pad_dot, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_pad_dot, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_pad_dot, 87 );
lv_obj_set_y( ui_pad_dot, 266 );
lv_obj_add_flag( ui_pad_dot, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pad_dot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label16 = lv_label_create(ui_pad_dot);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, 11 );
lv_obj_set_y( ui_Label16, 7 );
lv_label_set_text(ui_Label16,".");
lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label16, &ui_font_Pix16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pnl_selected = lv_img_create(ui_Screen1);
lv_img_set_src(ui_pnl_selected, &ui_img_selected_png);
lv_obj_set_width( ui_pnl_selected, 13);
lv_obj_set_height( ui_pnl_selected, 13);
lv_obj_set_x( ui_pnl_selected, 9 );
lv_obj_set_y( ui_pnl_selected, 96 );
lv_obj_add_flag( ui_pnl_selected, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pnl_selected, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
