// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: moon phase

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void moon_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Screen1_Label_bootscreen;
lv_obj_t *ui_Screen1_Container_Container;
lv_obj_t *ui_Screen1_Label_sunrise;
lv_obj_t *ui_Screen1_Label_sunset;
lv_obj_t *ui_Screen1_Label_moonrise;
lv_obj_t *ui_Screen1_Label_moonset;
lv_obj_t *ui_Screen1_Label_Phase;
lv_obj_t *ui_Screen1_Panel_border;
lv_obj_t *ui_Screen1_Label_date;
lv_obj_t *ui_Screen1_Label_sec;
lv_obj_t *ui_Screen1_Label_ampm;
lv_obj_t *ui_Screen1_Label_time;
lv_obj_t *ui_Screen1_Image_sun_moon;
lv_obj_t *ui_Screen1_Image_bootscreeni;
lv_obj_t *ui_Screen1_Image_Moon;
lv_obj_t *ui_Startevents____initial_actions0;
const lv_img_dsc_t *ui_imgset_moon_[30] = {
&ui_img_moon_phase_moon_1_png,
&ui_img_moon_phase_moon_2_png,
&ui_img_moon_phase_moon_3_png,
&ui_img_moon_phase_moon_4_png,
&ui_img_moon_phase_moon_5_png,
&ui_img_moon_phase_moon_6_png,
&ui_img_moon_phase_moon_7_png,
&ui_img_moon_phase_moon_8_png,
&ui_img_moon_phase_moon_9_png,
&ui_img_moon_phase_moon_10_png,
&ui_img_moon_phase_moon_11_png,
&ui_img_moon_phase_moon_12_png,
&ui_img_moon_phase_moon_13_png,
&ui_img_moon_phase_moon_14_png,
&ui_img_moon_phase_moon_15_png,
&ui_img_moon_phase_moon_16_png,
&ui_img_moon_phase_moon_17_png,
&ui_img_moon_phase_moon_18_png,
&ui_img_moon_phase_moon_19_png,
&ui_img_moon_phase_moon_20_png,
&ui_img_moon_phase_moon_21_png,
&ui_img_moon_phase_moon_22_png,
&ui_img_moon_phase_moon_23_png,
&ui_img_moon_phase_moon_24_png,
&ui_img_moon_phase_moon_25_png,
&ui_img_moon_phase_moon_26_png,
&ui_img_moon_phase_moon_27_png,
&ui_img_moon_phase_moon_28_png,
&ui_img_moon_phase_moon_29_png,
&ui_img_moon_phase_moon_30_png
};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void moon_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = ui_imgset_moon_;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_moon_)/(sizeof(lv_img_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 3000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame );
lv_anim_set_values(&PropertyAnimation_0, 1, 28 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Startevents____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
