// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: moon phase

#ifndef _MOON_PHASE_UI_H
#define _MOON_PHASE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void moon_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Screen1_Label_bootscreen;
extern lv_obj_t *ui_Screen1_Container_Container;
extern lv_obj_t *ui_Screen1_Label_sunrise;
extern lv_obj_t *ui_Screen1_Label_sunset;
extern lv_obj_t *ui_Screen1_Label_moonrise;
extern lv_obj_t *ui_Screen1_Label_moonset;
extern lv_obj_t *ui_Screen1_Label_Phase;
extern lv_obj_t *ui_Screen1_Panel_border;
extern lv_obj_t *ui_Screen1_Label_date;
extern lv_obj_t *ui_Screen1_Label_sec;
extern lv_obj_t *ui_Screen1_Label_ampm;
extern lv_obj_t *ui_Screen1_Label_time;
extern lv_obj_t *ui_Screen1_Image_sun_moon;
extern lv_obj_t *ui_Screen1_Image_bootscreeni;
extern lv_obj_t *ui_Screen1_Image_Moon;
extern lv_obj_t *ui_Startevents____initial_actions0;

LV_IMG_DECLARE( ui_img_368594647);   // assets/Icons/Sun & Moon.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_1_png);   // assets/Moon_Phase/Moon_1.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_10_png);   // assets/Moon_Phase/Moon_10.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_11_png);   // assets/Moon_Phase/Moon_11.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_12_png);   // assets/Moon_Phase/Moon_12.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_13_png);   // assets/Moon_Phase/Moon_13.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_14_png);   // assets/Moon_Phase/Moon_14.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_15_png);   // assets/Moon_Phase/Moon_15.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_16_png);   // assets/Moon_Phase/Moon_16.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_17_png);   // assets/Moon_Phase/Moon_17.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_18_png);   // assets/Moon_Phase/Moon_18.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_19_png);   // assets/Moon_Phase/Moon_19.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_2_png);   // assets/Moon_Phase/Moon_2.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_20_png);   // assets/Moon_Phase/Moon_20.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_21_png);   // assets/Moon_Phase/Moon_21.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_22_png);   // assets/Moon_Phase/Moon_22.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_23_png);   // assets/Moon_Phase/Moon_23.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_24_png);   // assets/Moon_Phase/Moon_24.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_25_png);   // assets/Moon_Phase/Moon_25.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_26_png);   // assets/Moon_Phase/Moon_26.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_27_png);   // assets/Moon_Phase/Moon_27.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_28_png);   // assets/Moon_Phase/Moon_28.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_29_png);   // assets/Moon_Phase/Moon_29.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_3_png);   // assets/Moon_Phase/Moon_3.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_30_png);   // assets/Moon_Phase/Moon_30.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_4_png);   // assets/Moon_Phase/Moon_4.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_5_png);   // assets/Moon_Phase/Moon_5.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_6_png);   // assets/Moon_Phase/Moon_6.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_7_png);   // assets/Moon_Phase/Moon_7.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_8_png);   // assets/Moon_Phase/Moon_8.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_9_png);   // assets/Moon_Phase/Moon_9.png


LV_FONT_DECLARE( ui_font_SG28);
LV_FONT_DECLARE( ui_font_SG50);
LV_FONT_DECLARE( ui_font_SR14);
LV_FONT_DECLARE( ui_font_SR16);
LV_FONT_DECLARE( ui_font_SR18);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
