// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Attitude indicator

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_dial_bg = lv_img_create(ui_Screen1);
lv_img_set_src(ui_img_dial_bg, &ui_img_images_dial_bg_png);
lv_obj_set_width( ui_img_dial_bg, LV_SIZE_CONTENT);  /// 170
lv_obj_set_height( ui_img_dial_bg, LV_SIZE_CONTENT);   /// 170
lv_obj_set_align( ui_img_dial_bg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_dial_bg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_dial_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_pitch_scale = lv_img_create(ui_Screen1);
lv_img_set_src(ui_img_pitch_scale, &ui_img_images_pitch_scale_png);
lv_obj_set_width( ui_img_pitch_scale, LV_SIZE_CONTENT);  /// 170
lv_obj_set_height( ui_img_pitch_scale, LV_SIZE_CONTENT);   /// 170
lv_obj_set_align( ui_img_pitch_scale, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_pitch_scale, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_pitch_scale, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_roll_scale = lv_img_create(ui_Screen1);
lv_img_set_src(ui_img_roll_scale, &ui_img_images_roll_scale_png);
lv_obj_set_width( ui_img_roll_scale, LV_SIZE_CONTENT);  /// 178
lv_obj_set_height( ui_img_roll_scale, LV_SIZE_CONTENT);   /// 178
lv_obj_set_align( ui_img_roll_scale, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_roll_scale, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_roll_scale, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_mask = lv_img_create(ui_Screen1);
lv_img_set_src(ui_img_mask, &ui_img_images_mask_png);
lv_obj_set_width( ui_img_mask, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_img_mask, LV_SIZE_CONTENT);   /// 170
lv_obj_set_align( ui_img_mask, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_mask, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_mask, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_dial = lv_img_create(ui_Screen1);
lv_img_set_src(ui_img_dial, &ui_img_images_dial_png);
lv_obj_set_width( ui_img_dial, LV_SIZE_CONTENT);  /// 200
lv_obj_set_height( ui_img_dial, LV_SIZE_CONTENT);   /// 170
lv_obj_set_align( ui_img_dial, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_dial, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_dial, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_pointer = lv_img_create(ui_Screen1);
lv_img_set_src(ui_img_pointer, &ui_img_images_pointer_png);
lv_obj_set_width( ui_img_pointer, LV_SIZE_CONTENT);  /// 84
lv_obj_set_height( ui_img_pointer, LV_SIZE_CONTENT);   /// 78
lv_obj_set_x( ui_img_pointer, 0 );
lv_obj_set_y( ui_img_pointer, -25 );
lv_obj_set_align( ui_img_pointer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_pointer, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_pointer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_roll = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label_roll, 46);
lv_obj_set_height( ui_Label_roll, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_roll, -130 );
lv_obj_set_y( ui_Label_roll, 0 );
lv_obj_set_align( ui_Label_roll, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_roll,"-90");
lv_obj_set_style_text_color(ui_Label_roll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_roll, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_roll, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_roll, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Label_roll, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label_roll, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label_roll, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Label_roll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Label_roll, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Label_roll, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Label_roll, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label_roll, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label_roll, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label_roll, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label_roll, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label__pitch = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label__pitch, 46);
lv_obj_set_height( ui_Label__pitch, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label__pitch, 130 );
lv_obj_set_y( ui_Label__pitch, 0 );
lv_obj_set_align( ui_Label__pitch, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label__pitch,"-20");
lv_obj_set_style_text_color(ui_Label__pitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label__pitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label__pitch, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label__pitch, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Label__pitch, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label__pitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label__pitch, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Label__pitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Label__pitch, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Label__pitch, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Label__pitch, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label__pitch, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label__pitch, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label__pitch, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label__pitch, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

}
