// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: moon phase

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label_bootscreen = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_Label_bootscreen, 175);
lv_obj_set_height( ui_Screen1_Label_bootscreen, 65);
lv_obj_set_x( ui_Screen1_Label_bootscreen, 73 );
lv_obj_set_y( ui_Screen1_Label_bootscreen, 1 );
lv_obj_set_align( ui_Screen1_Label_bootscreen, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_Label_bootscreen,"Moon Phase Clock");
lv_obj_set_style_text_align(ui_Screen1_Label_bootscreen, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label_bootscreen, &ui_font_SG28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Container_Container = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Screen1_Container_Container);
lv_obj_set_width( ui_Screen1_Container_Container, 201);
lv_obj_set_height( ui_Screen1_Container_Container, 170);
lv_obj_set_x( ui_Screen1_Container_Container, 118 );
lv_obj_set_y( ui_Screen1_Container_Container, 0 );
lv_obj_clear_flag( ui_Screen1_Container_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Screen1_Label_sunrise = lv_label_create(ui_Screen1_Container_Container);
lv_obj_set_width( ui_Screen1_Label_sunrise, 65);
lv_obj_set_height( ui_Screen1_Label_sunrise, 15);
lv_obj_set_x( ui_Screen1_Label_sunrise, 16 );
lv_obj_set_y( ui_Screen1_Label_sunrise, 146 );
lv_label_set_text(ui_Screen1_Label_sunrise,"");
lv_obj_set_style_text_align(ui_Screen1_Label_sunrise, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label_sunrise, &ui_font_SR14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label_sunset = lv_label_create(ui_Screen1_Container_Container);
lv_obj_set_width( ui_Screen1_Label_sunset, 68);
lv_obj_set_height( ui_Screen1_Label_sunset, 15);
lv_obj_set_x( ui_Screen1_Label_sunset, 131 );
lv_obj_set_y( ui_Screen1_Label_sunset, 146 );
lv_label_set_text(ui_Screen1_Label_sunset,"");
lv_obj_set_style_text_align(ui_Screen1_Label_sunset, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label_sunset, &ui_font_SR14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label_moonrise = lv_label_create(ui_Screen1_Container_Container);
lv_obj_set_width( ui_Screen1_Label_moonrise, 65);
lv_obj_set_height( ui_Screen1_Label_moonrise, 15);
lv_obj_set_x( ui_Screen1_Label_moonrise, 16 );
lv_obj_set_y( ui_Screen1_Label_moonrise, 121 );
lv_label_set_text(ui_Screen1_Label_moonrise,"");
lv_obj_set_style_text_align(ui_Screen1_Label_moonrise, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label_moonrise, &ui_font_SR14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label_moonset = lv_label_create(ui_Screen1_Container_Container);
lv_obj_set_width( ui_Screen1_Label_moonset, 68);
lv_obj_set_height( ui_Screen1_Label_moonset, 15);
lv_obj_set_x( ui_Screen1_Label_moonset, 131 );
lv_obj_set_y( ui_Screen1_Label_moonset, 121 );
lv_label_set_text(ui_Screen1_Label_moonset,"");
lv_obj_set_style_text_align(ui_Screen1_Label_moonset, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label_moonset, &ui_font_SR14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label_Phase = lv_label_create(ui_Screen1_Container_Container);
lv_obj_set_width( ui_Screen1_Label_Phase, 168);
lv_obj_set_height( ui_Screen1_Label_Phase, 20);
lv_obj_set_x( ui_Screen1_Label_Phase, 25 );
lv_obj_set_y( ui_Screen1_Label_Phase, 89 );
lv_label_set_long_mode(ui_Screen1_Label_Phase,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_Screen1_Label_Phase,"");
lv_obj_set_style_text_align(ui_Screen1_Label_Phase, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label_Phase, &ui_font_SR18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Panel_border = lv_obj_create(ui_Screen1_Container_Container);
lv_obj_set_width( ui_Screen1_Panel_border, 169);
lv_obj_set_height( ui_Screen1_Panel_border, 27);
lv_obj_set_x( ui_Screen1_Panel_border, 11 );
lv_obj_set_y( ui_Screen1_Panel_border, 14 );
lv_obj_set_align( ui_Screen1_Panel_border, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Screen1_Panel_border, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Screen1_Panel_border, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Screen1_Panel_border, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Screen1_Panel_border, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1_Panel_border, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Screen1_Panel_border, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Screen1_Panel_border, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Screen1_Panel_border, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label_date = lv_label_create(ui_Screen1_Container_Container);
lv_obj_set_width( ui_Screen1_Label_date, 159);
lv_obj_set_height( ui_Screen1_Label_date, 21);
lv_obj_set_x( ui_Screen1_Label_date, 31 );
lv_obj_set_y( ui_Screen1_Label_date, 59 );
lv_label_set_long_mode(ui_Screen1_Label_date,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_Screen1_Label_date,"");
lv_obj_set_style_text_align(ui_Screen1_Label_date, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label_date, &ui_font_SR18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label_sec = lv_label_create(ui_Screen1_Container_Container);
lv_obj_set_width( ui_Screen1_Label_sec, 28);
lv_obj_set_height( ui_Screen1_Label_sec, 20);
lv_obj_set_x( ui_Screen1_Label_sec, 163 );
lv_obj_set_y( ui_Screen1_Label_sec, 34 );
lv_label_set_text(ui_Screen1_Label_sec,"");
lv_obj_set_style_text_align(ui_Screen1_Label_sec, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label_sec, &ui_font_SR18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label_ampm = lv_label_create(ui_Screen1_Container_Container);
lv_obj_set_width( ui_Screen1_Label_ampm, 30);
lv_obj_set_height( ui_Screen1_Label_ampm, 20);
lv_obj_set_x( ui_Screen1_Label_ampm, 162 );
lv_obj_set_y( ui_Screen1_Label_ampm, 12 );
lv_label_set_text(ui_Screen1_Label_ampm,"");
lv_obj_set_style_text_align(ui_Screen1_Label_ampm, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label_ampm, &ui_font_SR18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Label_time = lv_label_create(ui_Screen1_Container_Container);
lv_obj_set_width( ui_Screen1_Label_time, 169);
lv_obj_set_height( ui_Screen1_Label_time, 45);
lv_obj_set_x( ui_Screen1_Label_time, -7 );
lv_obj_set_y( ui_Screen1_Label_time, 8 );
lv_label_set_text(ui_Screen1_Label_time,"");
lv_obj_set_style_text_align(ui_Screen1_Label_time, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1_Label_time, &ui_font_SG50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1_Image_sun_moon = lv_img_create(ui_Screen1_Container_Container);
lv_img_set_src(ui_Screen1_Image_sun_moon, &ui_img_368594647);
lv_obj_set_width( ui_Screen1_Image_sun_moon, LV_SIZE_CONTENT);  /// 39
lv_obj_set_height( ui_Screen1_Image_sun_moon, LV_SIZE_CONTENT);   /// 45
lv_obj_set_x( ui_Screen1_Image_sun_moon, 6 );
lv_obj_set_y( ui_Screen1_Image_sun_moon, 55 );
lv_obj_set_align( ui_Screen1_Image_sun_moon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Screen1_Image_sun_moon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Screen1_Image_sun_moon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Screen1_Image_bootscreeni = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_Image_bootscreeni, 170);
lv_obj_set_height( ui_Screen1_Image_bootscreeni, 170);
lv_obj_add_flag( ui_Screen1_Image_bootscreeni, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Screen1_Image_bootscreeni, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Screen1_Image_Moon = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_Image_Moon, 170);
lv_obj_set_height( ui_Screen1_Image_Moon, 170);
lv_obj_add_flag( ui_Screen1_Image_Moon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Screen1_Image_Moon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
