// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: PV Dashboard

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void rotation_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Cont_guage_home;
lv_obj_t *ui_img_guage_home;
lv_obj_t *ui_img_needle_home;
lv_obj_t *ui_Label_home_kV;
lv_obj_t *ui_Cont_guage_pv;
lv_obj_t *ui_img_guage_pv;
lv_obj_t *ui_img_needle_pv;
lv_obj_t *ui_Label_pv_kV;
lv_obj_t *ui_Cont_power;
lv_obj_t *ui_img_outline_power;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Cont_kWh;
lv_obj_t *ui_img_outline_kWh;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Chart_TP;
lv_obj_t *ui_Cont_battery;
lv_obj_t *ui_img_battery_fill;
lv_obj_t *ui_img_battery_knob;
lv_obj_t *ui_img_battery_icon;
lv_obj_t *ui_Cont_mV_bar;
lv_obj_t *ui_img_mv_bar;
lv_obj_t *ui_img_mv_bar_knob;
lv_obj_t *ui_Cont_TP;
lv_obj_t *ui_Label_TP;
lv_obj_t *ui_Label_TP1;
lv_obj_t *ui_Cont_CH;
lv_obj_t *ui_Label_CH;
lv_obj_t *ui_Label_CH1;
lv_obj_t *ui_Cont_CA;
lv_obj_t *ui_Label_CA;
lv_obj_t *ui_Label_CA1;
lv_obj_t *ui_Cont_Bat_label;
lv_obj_t *ui_Label_bat;
lv_obj_t *ui_Label_Per;
lv_obj_t *ui_Cont_mV_label;
lv_obj_t *ui_Label_mV;
lv_obj_t *ui_Label_mV1;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void rotation_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 1800 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
