// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Digital Pricetag

#ifndef _DIGITAL_PRICETAG_UI_H
#define _DIGITAL_PRICETAG_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void wifi_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_screen_wifi
void ui_screen_wifi_screen_init(void);
void ui_event_screen_wifi( lv_event_t * e);
extern lv_obj_t *ui_screen_wifi;
extern lv_obj_t *ui_Img_wifi;
extern lv_obj_t *ui_Label_wifi;
// SCREEN: ui_screen_tag
void ui_screen_tag_screen_init(void);
extern lv_obj_t *ui_screen_tag;
extern lv_obj_t *ui_Label_product;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel_save;
extern lv_obj_t *ui_label_now_price;
extern lv_obj_t *ui_label_was_price;
extern lv_obj_t *ui_label_save_value;
extern lv_obj_t *ui_label_per;
extern lv_obj_t *ui_label_save;
extern lv_obj_t *ui_img_barcode;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_wifi_icon_wifi_1_png);   // assets/wifi_icon/wifi_1.png
LV_IMG_DECLARE( ui_img_img_code_png);   // assets/img/code.png
LV_IMG_DECLARE( ui_img_wifi_icon_wifi_2_png);   // assets/wifi_icon/wifi_2.png
LV_IMG_DECLARE( ui_img_wifi_icon_wifi_3_png);   // assets/wifi_icon/wifi_3.png
LV_IMG_DECLARE( ui_img_wifi_icon_wifi_4_png);   // assets/wifi_icon/wifi_4.png

LV_FONT_DECLARE( ui_font_g22);
LV_FONT_DECLARE( ui_font_g26);
LV_FONT_DECLARE( ui_font_g28);
LV_FONT_DECLARE( ui_font_g30);
LV_FONT_DECLARE( ui_font_g50);
LV_FONT_DECLARE( ui_font_g60);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
